### ISSUE TITLE
Unable to login to admin

### ISSUE THREAD

**Issue by snyasr** [m7md3omer/ecommerce-laravel-fullstack#40]
I am new to laravel. Ive cloned the app locally but im unable to login using the given admin credentials - admin@admin.com and password.

Please assist.
Thanks

**Comment by sesos1232020** [comment]
same problem

**Comment by mhmdomer** [comment]
Please follow the installation guide (especially the command `php artisan ecommerce:install`)  and you will be able to login with the credentials:
email: admin@admin.com
password: password

Note that these credentials are different in http://vampireecommerce.herokuapp.com/ and you can't use them to login to the admin panel, they are only meant to be used locally.

**Comment by mhmdomer** [comment]
Seems like this is a problem with copying dummy files from the public folder to the storage folder https://github.com/mhmdomer/ecommerce-laravel/blob/e40c4def1db9537f56d6890a44d7cabe17a7d4d2/app/Console/Commands/EcommerceInstall.php#L59
https://github.com/mhmdomer/ecommerce-laravel/blob/e40c4def1db9537f56d6890a44d7cabe17a7d4d2/app/Console/Commands/EcommerceInstall.php#L60

If someone has a windows machine, please feel free to create a PR to make the copying process work on windows as well (Windows uses backspaces for file paths while other OSs use forward spaces)

**Comment by projectwehelp** [comment]
hope you tried the db seeding ?    php artisan db:seed  

this will add the dummy data to the database
